### ISSUE TITLE
Enable caching

### ISSUE THREAD

**Issue by C-Otto** [jjohannes/extra-java-module-info#11]
It seems there is no caching (enabled) according to output like this:

```
Caching disabled for ExtraModuleInfoTransform: /home/cotto/.gradle/caches/modules-2/files-2.1/org.springframework.shell/spring-shell-standard-commands/2.0.0.RELEASE/bd93b17640a669c9f2364acb592f271d930b9d5d/spring-shell-standard-commands-2.0.0.RELEASE.jar because:
  Caching not enabled.
```

If it is feasible, please cache this work to further decrease build time. Thanks a lot for the tool and your help!

**Comment by jjohannes** [comment]
This was an oversight. Thank you very much for pointing it out @C-Otto! Will be fixed in `0.6`.
