### ISSUE TITLE
Question around JPMS in a multi module project

### ISSUE THREAD

**Issue by ksp17788** [jjohannes/extra-java-module-info#18]
Background: I am trying to work with a multi module project where a library within that project contains a dependency on a legacy jar (with no module-info.java). When I try to use the `extraJavaModuleInfo` plugin, everything works well within the library context. I then use that library in an application (contains main method). I include the dependency on the library using `implementation(project(":<lib>"))`. I then build and install the application. In the `build/install/lib` folder of the application, I see that the library that I modified using `extraJavaModuleInfo` has not been copied into the folder. Instead the original one has been copied. Secondly, the shell script for the application at `build/install/bin/<appName>` contains `CLASSPATH` set instead of `MODULEPATH` being set for all dependencies. 

Question: Is this expected behavior for this plugin ?

Assumption: I would assume that the plugin would copy the modified jar into the lib folder and put all the jars in the module path. 

Example: To illustrate my findings, i am attaching the zip file for the project.
[sample_java_modules_multi_project-kotlin-dsl-copy.zip](https://github.com/jjohannes/extra-java-module-info/files/7138639/sample_java_modules_multi_project-kotlin-dsl-copy.zip)
 
Please let me know if i am doing something wrong. Thanks. 

Info:
```

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.7 (AdoptOpenJDK 11.0.7+10)
OS:           Mac OS X 10.16 x86_64

```

**Comment by jjohannes** [comment]
@ksp17788 Thanks for asking. This can indeed be confusing.

This plugin hooks into the dependency resolution of Gradle, effectively transforming Jars the moment before they are used. This is happening "inside" each subproject - e.g. just before the classpath/modulepath for the compile or for the start script tasks are computed.

This means you should apply **the same rules to all subprojects**.

Concretely this means you should apply the plugin in the convention plugin and define the rules there. In your example, you should move the plugin application to `/buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts`:

```
plugins {
    java
    id("de.jjohannes.extra-java-module-info")
}

extraJavaModuleInfo {
  ...
}
```

For this to work you need to add a dependency to the library providing the plugin to the `buildSrc/build.gradle.kts` (this is poorly documented in Gradle itself right now, but it's the way to go):

```
plugins {
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
}

dependencies {
    implementation("de.jjohannes.gradle:extra-java-module-info:0.9")
}
```

I should update the README to state this. I will keep this issue open until I have done that.

**Comment by jjohannes** [comment]
README updated. Thanks again @ksp17788 for making me aware.

**Comment by ksp17788** [comment]
Thank you. Very helpful.
