### ISSUE TITLE
Custom automatic module exports a package that it should not

### ISSUE THREAD

**Issue by ogrammer** [jjohannes/extra-java-module-info#19]
When I add `id 'de.jjohannes.extra-java-module-info' version '0.9'` to plugins, even without adding an `extraJavaModuleInfo`, all the JavaFX imports break. The `require`s in module-info still work but I can't import any classes. I use the plugin org.openjfx.javafxplugin 0.0.10 and Gradle 7.1. It also throws a ton of errors about "not a module and no descriptor" when I try to run, I think those come from the dependency I am using but why would I have to add extra info to dependencies of a dependency?

**Comment by ogrammer** [comment]
I added `failOnMissingModuleInfo.set(false)` and at least I can use the actually module libraries now but the automaticModule causes many errors like this: `error: the unnamed module/module ... reads package retrofit2 from both (automatic module) and retrofit2`

**Comment by jjohannes** [comment]
Hi @ogrammer. This sounds like you have two versions of `retrofit2` on your classpath. It's unlikely a direct issue with this plugin, but with the overall classpath setup and dependency resolution result.

This plugin can only help to add additional module information. To get a concise working setup, you have to be very careful which information you add for which legacy libraries. If you have a split package situation (which the error indicates) it very much depends on what exactly you want to achieve to find a proper solution. And some libraries are just not ready to be used as modules - e.g. if they lead to split packages.

But I am happy to have a look. Can you please share a full reproducer of the problem? And/Or run the build with `--scan` and share the link to the builds scan?

**Comment by ogrammer** [comment]
Thanks for replying @jjohannes. I checked the dependencies and only one dependency uses retrofit2, but there are 2 libraries that have packages in the same package. For example, library 1 has com.library.pkg and library 2 has com.library.pkg2. Not sure how to fix it.. "depends on what exactly you want to achieve to find a proper solution" I just want it to work, not sure if that answers it.

**Comment by ogrammer** [comment]
I had to drop modules for this project, I don't know if it will cause me problems when I will make installers but those 2 libraries are vital for this application. Thanks for identifying the issue
