### ISSUE TITLE
Use automatic module name for all packages without module information

### ISSUE THREAD

**Issue by Burtan** [jjohannes/extra-java-module-info#3]
Hi,
I have troubles running my modular app with different dependencies. While many legacy jars have an automatic module name, I have to use this plugin to be able to use org.simpleframework.simple-xml. This works, but now I have to add custom module info for every dependency that just worked before adding this plugin. 

```
Failed to transform kotlin-stdlib-jdk7-1.3.11.jar (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.11) to match attributes {artifactType=jar, javaModule=true, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for ExtraModuleInfoTransform: C:\Users\Frede\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.3.11\4839661cf6ce3c14b65ed7dcf5b9249b44ecca16\kotlin-stdlib-jdk7-1.3.11.jar.
         > Not a module and no mapping defined: kotlin-stdlib-jdk7-1.3.11.jar
```

This can easily be 100+ entries. Wouldn't it be reasonable to automatically generate the automaticModule info base on the jar name? For the example abouve this would be:
```
automaticModule("kotlin-stdlib-jdk7-1.3.11.jar", "kotlin.stdlib.jdk7")
```

**Comment by jjohannes** [comment]
@Burtan can you upgrade to Kotlin 1.4? It is supposed to have full module descriptors in all jars.

**Comment by Burtan** [comment]
I can do that, it's mostly dependencies that use <1.4, so I have to exclude those.

**Comment by jjohannes** [comment]
@Burtan version `0.3` of the plugin now has an option to disable the error. Jars without any infos the stay untouched.

```
extraJavaModuleInfo {
    failOnMissingModuleInfo.set(false)
}
```
