### ISSUE TITLE
Add license information to package to be approved within corporate artifactory

### ISSUE THREAD

**Issue by EM-Creations** [jjohannes/extra-java-module-info#32]
Hi,

This is some great work you've done here and I'd like to use this dependency in my job however it's not available behind our corporate artifactory the reason being its failing an internal check as part of a Jenkins build job. It's failing due to "No license url present" and "No license name present" in the package's pom file. 

I assume this is just some extra information you need to include in the published package. Is this something you can do please?

Thank you.

**Comment by jjohannes** [comment]
Thank you for reporting this @EM-Creations. I added the license information (and some more informal metadata) to the POM files. Please let me know if this fixes your issue, then I will do the same for my other plugins. 

It is released in version `0.13`.
